version: 2
jobs:
  plan_terraform:
    docker:
      - image: hashicorp/terraform:0.11.8
    steps:
      - checkout
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Initialize Terraform
          command: cd terraform && terraform init
  apply_terraform:
    requires: hold
    docker:
      - image: hashicorp/terraform:0.11.8
    steps:
      - checkout
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Apply Terraform
          command: cd terraform && terraform plan
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: |
          sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

workflows:
  version: 2
  terraform:
    jobs:
      - plan_terraform
      - hold:
          type: approval
          requires:
            - plan_terraform
      - apply_terraform:
          requires:
            - hold

